source "https://rubygems.org"

gem "cocoapods"
gem 'fastlane'
gem 'xcodeproj'
gem 'synx'
gem 'xcode-install'
gem 'pry'
gem 'danger'
gem 'danger-swiftlint'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
